# use the server address from the EU proxy as default
serverAddr = "{{ or .Envs.SERVER_ADDR "34.159.153.198" }}"
serverPort = 7000
auth.method = "token"
auth.token = "aWKF58f3wQgSSMzcNLoYexYyp3y9QsDG6"

webServer.addr = "127.0.0.1"
webServer.port = 7400
# use first 10 chars of key as user (makes also the name unique)
user = "{{ printf "%.10s" .Envs.APIKEY }}"

metadatas.apikey = "{{ .Envs.APIKEY }}"
metadatas.proxyuser = "{{ .Envs.PROXY_USER }}"
metadatas.proxypass = "{{ .Envs.PROXY_PASS }}"
metadatas.type = "plw"

[[proxies]]
name = "{{ .Envs.PLW_NAME }}"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3128