name: Docker Image CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: build and push
      env: # Or as an environment variable
        JSON_KEY: ${{ secrets.JSON_KEY }}
      run: |
        echo "Building and pushing $RELEASE_VERSION"
        cat $JSON_KEY | docker login -u _json_key --password-stdin https://europe-docker.pkg.dev
        docker build . --file Dockerfile --tag eu.gcr.io/octomind-dev/plw:$RELEASE_VERSION
        docker push eu.gcr.io/octomind-dev/plw:$RELEASE_VERSION
