name: Docker Image CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: build and push
      env: # Or as an environment variable
        JSON_KEY_B64: ${{ secrets.JSON_KEY_B64 }}
      run: |
        echo "Building and pushing $RELEASE_VERSION"
        echo "$JSON_KEY_B64" | docker login -u _json_key_base64 --password-stdin https://europe-docker.pkg.dev
        docker build . -f Dockerfile -t europe-docker.pkg.dev/octomind-dev/eu.gcr.io/plw:$RELEASE_VERSION -t europe-docker.pkg.dev/octomind-dev/eu.gcr.io/plw:latest
        docker push -a europe-docker.pkg.dev/octomind-dev/eu.gcr.io/plw:$RELEASE_VERSION
        
